apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webfrontend
  namespace: argocd1
spec:
  project: default

  source:
    repoURL: https://github.com/mandarpalsodkar/dev-spaces.git
    targetRevision: master
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: webfrontend
  syncPolicy:
    syncOptions:
    - Createnamespace=false

  # path to the yaml manifests
  path: webfrontend/{{releasename}}/
  helm:
    passCredentials: true
    valueFiles:
      - ../common.values.yaml
      - values.yaml

  
  #  automated:
  #    selfHeal: true
  #    prune: true


