# file: development/common-values.yaml.
apiVersion: v1
kind: application
common:
  autoscaling:
  - name: minReplicas
    value: "2"
  - name: maxReplicas
    value: "102"
  image:  
  - name: repository
    value: mplin2.azurecr.io/
