# file: templates/_deployment.yaml
apiVersion: apps/v2
kind: Deployment
metadata:
  name: {{ include "webfrontend._deployment" . }}
env:
{{- toYaml .Values.autoscaling | nindent 12 }}
{{- end }}
# Template of common container env variables
{{- if .Values.common.autoscaling }}
{{- toYaml .Values.common.autoscaling | nindent 12 }}
{{- end }}