{{- define "library.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfrontenddeploy
  labels:
    app: argotest
spec:
  selector:
    matchLabels:
      app: argotest
  template:
    metadata:
      labels:
        app: argotest
    spec:
      containers:
        - name: webfrontend
          image: "{{ if .Values.image.repository }}{{ .Values.image.repository }}{{ else }}{{ .Values.image_1.repository_1 }}{{ end }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
{{- end }}          
